# Generated by Django 4.1.4 on 2022-12-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='razor_pay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='razor_pay_payment_signature',
            new_name='razorpay_payment_signature',
        ),
    ]
