# Generated by Django 4.1.4 on 2022-12-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_razor_pay_order_id_cart_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_payment_signature',
            new_name='razorpay_signature',
        ),
    ]
